# GitHub Actions 的名称
name: GitHub Actions SpringBoot Demo

# 当 master 分支发生 push 或者 pull request 事件时触发 action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 指定 jobs
jobs:
  # build job
  build:

    # 指定运行在 ubuntu 上
    runs-on: ubuntu-latest
    steps:

      # 把仓库代码拉到 ubuntu 镜像上
      - uses: actions/checkout@v2

      # 指定 java 版本
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

#      # 给 gradle 赋予可运行权限
#      - name: Grant execute permission for mvn
#        run: chmod +x mvn

      # 通过 gradle 打包我们的项目
      - name: Build with maven
        run: mvn clean package -Dmaven.test.skip=true

      # 通过 Dockerfile 构建镜像
      - name: Build docker image
        run: docker build . -t {{ image_name:image_version }}

      # 登陆到我们自己的 docker registry
      - name: Login to huaweiyun docker image registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_SECRET }} ${{ secrets.DOCKER_REPOSITORY }}

      # 上传 docker 镜像
      - name: Push image to huaweiyun docker image registry
        run: docker push {{ image_name:image_version }}
